
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async enableBlur() : Promise<void> {
    await TAURI_INVOKE("enable_blur");
},
async disableBlur() : Promise<void> {
    await TAURI_INVOKE("disable_blur");
},
async getHeaderInfo() : Promise<Result<HeaderInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_header_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLastHitBossName() : Promise<string | null> {
    return await TAURI_INVOKE("get_last_hit_boss_name");
},
async getCrowdsourcedMonster() : Promise<CrowdsourcedMonster | null> {
    return await TAURI_INVOKE("get_crowdsourced_monster");
},
async getCrowdsourcedMonsterOptions() : Promise<CrowdsourcedMonsterOption[]> {
    return await TAURI_INVOKE("get_crowdsourced_monster_options");
},
async setCrowdsourcedMonsterRemote(remoteId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_crowdsourced_monster_remote", { remoteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLocalPlayerLine() : Promise<Result<number | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_local_player_line") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markCurrentCrowdsourcedLineDead() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_current_crowdsourced_line_dead") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetEncounter() : Promise<void> {
    await TAURI_INVOKE("reset_encounter");
},
async togglePauseEncounter() : Promise<void> {
    await TAURI_INVOKE("toggle_pause_encounter");
},
async hardReset() : Promise<void> {
    await TAURI_INVOKE("hard_reset");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type CrowdsourcedMonster = { name: string; id: number; remote_id: string | null }
export type CrowdsourcedMonsterOption = { name: string; id: number; remote_id: string }
export type HeaderInfo = { totalDmg: number; elapsedMs: number; timeLastCombatPacketMs: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
